# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Docker Ansible role.
#
# The Webarchitects Docker Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Docker Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Docker Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Uninstall Docker Compose version 1.x and compose-switch
  block:

    - name: Docker Compose apt package absent
      ansible.builtin.apt:
        pkg:
          - docker-compose
        state: absent

    - name: Docker Compose version 1 absent
      ansible.builtin.file:
        path: "{{ path }}"
        state: absent
      loop:
        - /usr/local/bin/docker-compose
        - /usr/local/bin/docker-compose-v1
        - /usr/local/bin/compose-switch
        - /etc/bash_completion.d/docker-compose
      loop_control:
        loop_var: path

    - name: Check if a docker-compose alternative exists
      ansible.builtin.command: update-alternatives --query docker-compose
      check_mode: false
      changed_when: false
      register: docker_compose_alternatives_query
      failed_when: docker_compose_alternatives_query.rc is not regex('^0|2')

    - name: Remove Docker Compose alternatives
      ansible.builtin.command: "{{ cmd }}"
      loop:
        - update-alternatives --remove docker-compose /usr/local/bin/docker-compose
        - update-alternatives --remove docker-compose /usr/local/bin/compose-switch
      loop_control:
        loop_var: cmd
      when: docker_compose_alternatives_query.rc == 0

  when: ( docker_compose_v1 is defined ) and ( not docker_compose_v1 | bool )
  tags:
    - docker
    - docker_compose_v1

- name: Install Docker Compose version 1.x and compose-switch
  block:

    - name: Which Docker Compose Version 1
      ansible.builtin.command: which docker-compose-v1
      check_mode: false
      changed_when: false
      register: docker_compose_v1_path
      failed_when: docker_compose_v1_path.rc is not regex('^0|1$')

    - name: When Docker Compose Version 1 is installed
      block:

        - name: Docker Compose Version 1 version
          ansible.builtin.command: docker-compose-v1 -v --no-ansi
          check_mode: false
          changed_when: false
          register: docker_compose_v1_version

        - name: Set a fact for Version 1 of Docker Compose that is installed
          ansible.builtin.set_fact:
            docker_compose_v1_installed: "{{ docker_compose_v1_version.stdout.split(' ')[2] | regex_replace(',$') }}"

        - name: Set a fact if a newer version of Docker Compose Version 1 is specified
          ansible.builtin.set_fact:
            docker_compose_v1_upgrade: true
          when: docker_compose_v1_installed is version(docker_compose_version_v1, '<')

      when: ( docker_compose_v1_path is defined ) and ( "docker-compose" in docker_compose_v1_path.stdout )

    - name: Install or upgrade Docker Compose Version 1
      block:

        - name: Gather Ansible hardware facts
          ansible.builtin.setup:
            gather_subset:
              - hardware

        - name: Temporary download directory registered
          ansible.builtin.tempfile:
            state: directory
            suffix: docker-compose
          register: docker_compose_v1_download_dir

        - name: Docker Compose Version 1 checksum present
          ansible.builtin.get_url:
            url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version_v1 }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}.sha256"
            dest: "{{ docker_compose_v1_download_dir.path }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}.sha256"
            owner: root
            group: root
            mode: 0644

        - name: Docker Compose Version 1 base64 encoded version sha256 checksum slurped
          ansible.builtin.slurp:
            src: "{{ docker_compose_v1_download_dir.path }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}.sha256"
          register: docker_compose_v1_sha256_b64encoded

        - name: Docker Compose Version 1 base64 encoded version of the sha256 checksum decoded
          ansible.builtin.set_fact:
            docker_compose_v1_sha256_file: "sha256:{{ docker_compose_v1_sha256_b64encoded['content'] | b64decode }}"

        - name: Docker Compose Version 1 sha256 checksum string first value following split on spaces
          ansible.builtin.set_fact:
            docker_compose_v1_sha256: "{{ docker_compose_v1_sha256_file.split(' ')[0] }}"

        - name: Docker Compose Version 1 present
          ansible.builtin.get_url:
            url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version_v1 }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
            dest: /usr/local/bin/docker-compose-v1
            force: true
            owner: root
            group: root
            mode: 0755
            checksum: "{{ docker_compose_v1_sha256 }}"

        - name: Check docker-compose version 1
          ansible.builtin.command: docker-compose-v1 --ansi=never version
          check_mode: false
          changed_when: false
          register: docker_compose_v1_check
          failed_when: ( docker_compose_v1_check.rc != 0 ) or ( docker_compose_version_v1 not in docker_compose_v1_check.stdout )

        - name: Docker Compose Version 1 Bash completion in place
          ansible.builtin.get_url:
            url: "https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version_v1 }}/contrib/completion/bash/docker-compose"
            dest: /etc/bash_completion.d/docker-compose
            force: true
            owner: root
            group: root
            mode: 0644

      when:
        - not ansible_check_mode | bool
        - ( docker_compose_v1_path.rc == 1 ) or ( docker_compose_v1_upgrade is defined and docker_compose_v1_upgrade | bool )

    - name: Check the latest version of Docker Compose Switch
      ansible.builtin.uri:
        url: https://github.com/docker/compose-switch/releases/latest
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: docker_compose_switch_headers

    - name: Debug Docker Compose Switch latest headers
      ansible.builtin.debug:
        msg:
          - "Location: {{ docker_compose_switch_headers.location }}"
          - "Path: {{ docker_compose_switch_headers.location | urlsplit('path') }}"
          - "Version: {{ docker_compose_switch_headers.location | urlsplit('path') | basename }}"
        verbosity: 2

    - name: Set a fact for the latest version of Docker Compose Switch
      ansible.builtin.set_fact:
        docker_compose_switch_latest: "{{ docker_compose_switch_headers.location | urlsplit('path') | basename }}"

    - name: Docker Compose Switch present
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose-switch/releases/download/{{ docker_compose_switch_latest }}/docker-compose-linux-{{ ansible_facts.ansible_local.dpkg.arch }}"
        dest: /usr/local/bin/compose-switch
        force: true
        owner: root
        group: root
        mode: 0755

    - name: Check docker-compose alternatives
      ansible.builtin.command: update-alternatives --display docker-compose
      check_mode: false
      changed_when: false
      register: docker_compose_alternatives_existing
      failed_when: docker_compose_alternatives_existing.rc is not regex('^0|2$')

    - name: Stat /usr/local/bin/docker-compose-v1
      ansible.builtin.stat:
        path: /usr/local/bin/docker-compose-v1
      register: docker_compose_v1_state

    - name: Set docker-compose-v1 alternative for docker-compose
      community.general.alternatives:
        name: docker-compose
        link: /usr/local/bin/docker-compose
        path: /usr/local/bin/docker-compose-v1
        priority: 1
      when:
        - docker_compose_v1_state.stat.exists | bool
        - ( "/usr/local/bin/docker-compose-v1 - priority 1" not in docker_compose_alternatives_existing.stdout_lines ) or ( docker_compose_alternatives_existing.rc != 0 )

    - name: Stat /usr/local/bin/docker-switch
      ansible.builtin.stat:
        path: /usr/local/bin/docker-compose-v1
      register: docker_compose_switch_state

    - name: Set compose-switch alternative for docker-compose
      community.general.alternatives:
        name: docker-compose
        link: /usr/local/bin/docker-compose
        path: /usr/local/bin/compose-switch
        priority: 99
      when:
        - docker_compose_switch_state.stat.exists | bool
        - ( "/usr/local/bin/compose-switch - priority 99" not in docker_compose_alternatives_existing.stdout_lines ) or ( docker_compose_alternatives_existing.rc != 0 )

    - name: Check compose-switch is working for docker-compose
      ansible.builtin.command: docker-compose --ansi=never version
      check_mode: false
      changed_when: false
      register: docker_compose_switch_check
      failed_when: ( docker_compose_switch_check.rc != 0 ) or ( "Docker Compose version" not in docker_compose_switch_check.stdout )
      when:
        - docker_compose_v1_state.stat.exists | bool
        - docker_compose_switch_state.stat.exists | bool

  when: ( docker_compose_v1 is defined ) and ( docker_compose_v1 | bool )
  tags:
    - docker
    - docker_compose_v1
...
