---
- name: Install Docker Compose
  block:

    - name: Remove Docker Composer version 1
      block:

        - name: Docker Compose version 1 absent
          ansible.builtin.file:
            path: /usr/local/bin/docker-compose
            state: absent

        - name: Docker Compose version 1 Bash completion absent
          ansible.builtin.file:
            path: /etc/bash_completion.d/docker-compose
            state: absent

        - name: Docker Compose apt package absent
          ansible.builtin.apt:
            pkg:
              - docker-compose
            state: absent

      when: not docker_compose_v1 | bool

    - name: Docker Compose present
      ansible.builtin.apt:
        pkg:
          - docker-compose-plugin
        state: present

    - name: Check the Docker Compose version that is available in the default PATH using docker compose
      ansible.builtin.command: docker compose --ansi=never version
      check_mode: false
      changed_when: false
      register: docker_compose_installed

    - name: Print the installed version of Docker Compose
      ansible.builtin.debug:
        var: docker_compose_installed.stdout

  tags:
    - docker-compose
...
