---
- name: Install Docker Compose
  block:

    - name: Remove Docker Composer version 1
      block:

        - name: Docker Compose version 1 absent
          file:
            path: /usr/local/bin/docker-compose
            state: absent

        - name: Docker Compose version 1 Bash completion absent
          file:
            path: /etc/bash_completion.d/docker-compose
            state: absent

      when: not docker_compose_v1 | bool

    - name: Docker Compose present
      apt:
        pkg:
          - docker-compose
        state: present

    - name: Check the Docker Compose version that is available in the default PATH using docker compose
      command: docker compose --ansi=never version
      check_mode: false
      changed_when: false

  tags:
    - docker-compose
...
