---
- name: Install Docker
  block:

    - name: Requirements present
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-docker
          - software-properties-common
        state: present

    - name: Python 2 package present
      ansible.builtin.apt:
        pkg:
          - python-docker
        state: present
        update_cache: false
      when: ansible_distribution_release is regex('stretch|buster')

    - name: Old Docker packages absent
      ansible.builtin.apt:
        pkg:
          - containerd
          - docker
          - docker-engine
          - docker.io
          - runc
        state: absent

    - name: Docker GPG key present
      ansible.builtin.apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Print the dpkg architecture
      ansible.builtin.command: dpkg --print-architecture
      check_mode: false
      changed_when: false
      register: docker_arch

    - name: Docker apt repo available
      ansible.builtin.template:
        src: docker.list.j2
        dest: /etc/apt/sources.list.d/docker.list
        mode: 0644
        owner: root
        group: root

    - name: Docker CE present
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Directory for Docker config present
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Docker configuration present
      ansible.builtin.template:
        src: templates/daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
      when: ( docker_nameservers is defined ) and ( docker_nameservers != [] )

    - name: Docker started
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

  tags:
    - docker
...
