---
- name: Install Docker
  block:

    - name: Requirements present
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-docker
          - software-properties-common
        state: present

    - name: Python 2 package present
      ansible.builtin.apt:
        pkg:
          - python-docker
        state: present
        update_cache: false
      when: ansible_distribution_release is regex('stretch|buster')

    - name: Legacy Docker packages absent
      ansible.builtin.apt:
        pkg:
          - containerd
          - docker
          - docker-engine
          - docker.io
          - runc
        autoclean: true
        autoremove: true
        state: absent

    - name: Legacy Docker apt sources list absent
      ansible.builtin.file:
        path: "{{ apt_list }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/download_docker_com_linux_debian.list
        - /etc/apt/sources.list.d/docker.list
      loop_control:
        loop_var: apt_list
        label: "{{ apt_list | basename }}"

    - name: Legacy Docker GPG key present
      ansible.builtin.apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: absent

    - name: Dependencies present
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - python3-docker
        state: present

    - name: Print the dpkg architecture
      ansible.builtin.command: dpkg --print-architecture
      check_mode: false
      changed_when: false
      register: docker_arch

    - name: Apt keyrings directory present
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Docker ascii armored gpg key present
      ansible.builtin.get_url:
        url: "{{ docker_gpg_url }}"
        checksum: "{{ docker_gpg_checksum }}"
        dest: /root/docker.asc
        mode: 0644
        owner: root
        group: root
      register: docker_gpg_asc_file

    - name: Stat Docker gpg asc file
      ansible.builtin.stat:
        path: /etc/apt/keyrings/docker.gpg
      register: docker_gpg_file

    - name: Docker gpg key dearmored
      ansible.builtin.shell: |
        set -e -o pipefail
        gpg --dearmor < /root/docker.asc > /etc/apt/keyrings/docker.gpg
      args:
        executable: "{% if ansible_distribution == 'Ubuntu' %}/usr/bin/bash{% elif ansible_distribution == 'Debian' %}/bin/bash{% endif %}"
      when: ( docker_gpg_asc_file.changed | bool ) or ( not docker_gpg_file.stat.exists | bool )

    - name: Docker gpg key check command
      ansible.builtin.command:
        gpg --with-colons
        {% if ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '<=') %}
        --with-fingerprint --with-subkey-fingerprint
        {% elif ansible_distribution == "Debian" and ansible_distribution_version is version('10.0', '<=') %}
        --with-fingerprint --with-subkey-fingerprint
        {% else %}
        --show-keys
        {% endif %}
        /etc/apt/keyrings/docker.gpg
      check_mode: false
      changed_when: false
      register: docker_gpg

    - name: Docker gpg key checked
      ansible.builtin.assert:
        that:
          - fpr in docker_gpg.stdout
      loop: "{{ docker_gpg_fingerprints }}"
      loop_control:
        extended: true
        loop_var: fpr
        label: "fingerprint {{ ansible_loop.index }}"

    - name: Docker apt repo available
      ansible.builtin.template:
        src: docker.sources.j2
        dest: /etc/apt/sources.list.d/docker.sources
        mode: 0644
        owner: root
        group: root

    - name: Docker apt preferences present
      ansible.builtin.template:
        src: docker.pref.j2
        dest: /etc/apt/preferences.d/docker.pref
        mode: 0644
        owner: root
        group: root

    - name: Docker CE present
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Directory for Docker config present
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Docker configuration present
      ansible.builtin.template:
        src: templates/daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
      when: ( docker_nameservers is defined ) and ( docker_nameservers != [] )
      notify: Restart docker

    - name: Docker started
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

  tags:
    - docker
...
