# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Docker Ansible role.
#
# The Webarchitects Docker Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Docker Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Docker Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as docker is false
  ansible.builtin.debug:
    msg: "The docker variable need to be true for the tasks in this role to run."
  when: >-
    ( docker is not defined ) or
    ( not docker | bool )
  tags:
    - docker

- name: Install Docker
  block:

    - name: Include Docker verify variables tasks
      ansible.builtin.include_tasks: verify.yml
      when:
        - docker_verify is defined
        - docker_verify | bool
      tags:
        - docker_verify

    - name: Include apt role local fact tasks if variables are not defined
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      when: >-
        ( ansible_local.dpkg.arch is not defined ) or
        ( ansible_local.gpg.version is not defined ) or
        ( ansible_local.bash.path is not defined )
      tags:
        - docker_apt
        - docker_compose_v1
        - docker_install
        - docker_local_facts

    - name: Include Docker apt tasks
      ansible.builtin.include_tasks: apt.yml
      tags:
        - docker_apt

    - name: Include Docker install and configure tasks
      ansible.builtin.include_tasks: install.yml
      tags:
        - docker_install

    - name: Include install Docker Compose version 1 tasks
      ansible.builtin.include_tasks: compose_v1.yml
      when: docker_compose_v1 is defined
      tags:
        - docker_compose_v1

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

  when:
    - docker is defined
    - docker | bool
  tags:
    - docker
...
