---
- name: Include local facts tasks
  ansible.builtin.include_tasks: local_facts.yml
  when: ansible_local.dpkg_arch is not defined
  tags:
    - docker
    - docker-compose

- name: Install Docker
  ansible.builtin.include_tasks: docker.yml
  when: ( docker is defined ) and ( docker | bool )
  tags:
    - docker

- name: Install Docker Compose
  ansible.builtin.include_tasks: compose.yml
  when: ( docker_compose is defined ) and ( docker_compose | bool )
  tags:
    - docker-compose

- name: Include Docker Compose Version 1 tasks
  ansible.builtin.include_tasks: compose_v1.yml
  when: ( docker_compose_v1 is defined ) and ( docker_compose_v1 | bool )
  tags:
    - docker-compose
...
