---
- name: Install Docker
  block:

    - name: Include Docker local facts tasks
      ansible.builtin.include_tasks: local_facts.yml
      when: ansible_local.dpkg_arch is not defined
      tags:
        - docker_local_facts

    - name: Include Docker apt tasks
      ansible.builtin.include_tasks: apt.yml
      tags:
        - docker_apt

    - name: Include Docker install and configure tasks
      ansible.builtin.include_tasks: install.yml
      tags:
        - docker_install

    - name: Include install Docker Compose version 1 tasks
      ansible.builtin.include_tasks: compose_v1.yml
      when: docker_compose_v1 is defined
      tags:
        - docker_compose_v1

  when: ( docker is defined ) and ( docker | bool )
  tags:
    - docker
...
