---
- name: Install Docker and optionally Docker Compose
  block:

    - name: Install Docker
      include_tasks: docker.yml

    - name: Install Docker Compose
      include_tasks: docker_compose.yml
      when: ( docker_compose is defined ) and ( docker_compose )
      tags:
        - docker-compose

  tags:
    - docker
...
